language: php

php:
    - '5.6'
    - '7.0'

env:
    global:
        - secure: "Wph3ma7in/E5NK/3RyZAYYBJOegvc7hcE6QqNBJ/jG1x2sr3TDRW3r3tKJhlo1usXKklpEDv8Y8pjtNmlN8wzJTUH09VLjyEtvW+7rFiN9c69oEPFGGS2ViShy9eHr8lwE4u4g9rr+7orbl8gJTC2St6vRGTq8PrVwtax36YqSk/Aq9atmyGqysN/ID14cBF2AZdQyyNOO9wVKWPE2B62u2fVndCRhDay2+/99t+XkB784vkI/AEDrSeqNP/0i3DY+5fggPY0DroCIOazeNvGq3mSKMI/I6T1VYWOZkPLElCXtOHBAI2TU0q1wqtmWzZTxUFM8R8GN6sZtc6B9Ab1tPGsrBacHkpRbLuh1kr6G5aTJSajcJh1kf7sHyc4Iuv2CaU56uX38q8SiZojuC0vi5Fn64BYCu+/nCvx1PyaEPRdzVD3YM0JhzHpcjSAU/MZi/mvMspy0Ly+caJyN/xLwMbKwdAWqMlGRfDqXGZd/+5o4EjS9tCkLsXP/wqmU3fCi5hsI+feYh/jSucNn1Qcjm3QkCqDrowd8bgCcdqRtztIqR1LrKDRDDMvcVpkcoDZ+zWLWCmrLdW8QpqI3SQ9Gl/E5fFIk3WwamRxb85G6E/s5IPpMVgA1CuU2hMqGUx9c+HYxtD4tcUPlHc6cuOGGSkOxWIOaCRt4/5henNoaw="
        - secure: "vnF3ywxO0GfpX0z78F3YWStU1DQzcVlzaLOlxFegdkbiPOeFAvPn8XCQ/gZOuumVo7N7M/i+84zjT2gfsgsRVskLjyJktIrXTMqP+B7sNJwXiB6uAdTJjX50LvmRvG3AJVAFKg1Blds6jK49OTV0ohX+uBZKl0A5mvyg9/q/iPlVrXH0AQQqLAhp9T/94eWBrqyKQnyKJn83SNUQWytwa+lgUa8fDfEO0iHBr2n3uwkXlTjh18pzqxZtPny1ySGpaksEa4CIxqAXbsytxdsLLu5nw2oHSbChWjtPgyaYbv3wgcFDjYLL5agARiPO12sCI0dSXNOTjagGn7ilsRhnpvuTG6T4QQJZTdju+yZgpdhRjPpClhiXU0pHCaGz+1ZNFO5ro5xAdZ25TBhi+g1Dc7FaAoLk5U/QYLgjt0RIgLsatPrGFHknBHCT4bxAVNiv8H4g4WuU7VtCDa0WBVwAH/zDzb8ueIniesq2nxntckieEq6bYM9EJweGZWoNBdaoHuSp/JZkBO51/P5ifNBzdyWBq9+hPBwdhq5SE4kD+u+tysXdvkNH1Cd/hW287cQcD8SP3rCKo5/MoaVWzHwanJja3I0g2cNQGS0DYYEQ8l1mtS4sr7u/f50wpEZA1gDlFxK/OsqVLjwT+eaCBed5QoyLNZMJWheIaG2kFK+Ov+A="

before_install:
    - composer self-update

install: composer install --no-interaction --no-progress

script: vendor/bin/behat -s twitter -v

notifications:
    slack: winegram:T3kUS19dsHZtwIe6GLF3dziO
